# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Service_pb2 as Service__pb2


class ServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.reverse = channel.unary_unary(
                '/Service/reverse',
                request_serializer=Service__pb2.ReverseMessage.SerializeToString,
                response_deserializer=Service__pb2.ReverseMessageResponse.FromString,
                )
        self.split = channel.unary_unary(
                '/Service/split',
                request_serializer=Service__pb2.SplitMessage.SerializeToString,
                response_deserializer=Service__pb2.SplitMessageResponse.FromString,
                )
        self.isprime = channel.stream_stream(
                '/Service/isprime',
                request_serializer=Service__pb2.IsPrimeMessage.SerializeToString,
                response_deserializer=Service__pb2.IsPrimeMessageResponse.FromString,
                )


class ServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def reverse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def split(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def isprime(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'reverse': grpc.unary_unary_rpc_method_handler(
                    servicer.reverse,
                    request_deserializer=Service__pb2.ReverseMessage.FromString,
                    response_serializer=Service__pb2.ReverseMessageResponse.SerializeToString,
            ),
            'split': grpc.unary_unary_rpc_method_handler(
                    servicer.split,
                    request_deserializer=Service__pb2.SplitMessage.FromString,
                    response_serializer=Service__pb2.SplitMessageResponse.SerializeToString,
            ),
            'isprime': grpc.stream_stream_rpc_method_handler(
                    servicer.isprime,
                    request_deserializer=Service__pb2.IsPrimeMessage.FromString,
                    response_serializer=Service__pb2.IsPrimeMessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def reverse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service/reverse',
            Service__pb2.ReverseMessage.SerializeToString,
            Service__pb2.ReverseMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def split(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service/split',
            Service__pb2.SplitMessage.SerializeToString,
            Service__pb2.SplitMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def isprime(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/Service/isprime',
            Service__pb2.IsPrimeMessage.SerializeToString,
            Service__pb2.IsPrimeMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
