# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rService.proto\"\x1e\n\x0eReverseMessage\x12\x0c\n\x04text\x18\x01 \x01(\t\")\n\x16ReverseMessageResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"+\n\x0cSplitMessage\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05\x64\x65lim\x18\x02 \x01(\t\"5\n\x14SplitMessageResponse\x12\x0e\n\x06number\x18\x01 \x01(\x05\x12\r\n\x05parts\x18\x02 \x03(\t\" \n\x0eIsPrimeMessage\x12\x0e\n\x06number\x18\x01 \x01(\x05\"&\n\x16IsPrimeMessageResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2\xa6\x01\n\x07Service\x12\x33\n\x07reverse\x12\x0f.ReverseMessage\x1a\x17.ReverseMessageResponse\x12-\n\x05split\x12\r.SplitMessage\x1a\x15.SplitMessageResponse\x12\x37\n\x07isprime\x12\x0f.IsPrimeMessage\x1a\x17.IsPrimeMessageResponse(\x01\x30\x01\x62\x06proto3')



_REVERSEMESSAGE = DESCRIPTOR.message_types_by_name['ReverseMessage']
_REVERSEMESSAGERESPONSE = DESCRIPTOR.message_types_by_name['ReverseMessageResponse']
_SPLITMESSAGE = DESCRIPTOR.message_types_by_name['SplitMessage']
_SPLITMESSAGERESPONSE = DESCRIPTOR.message_types_by_name['SplitMessageResponse']
_ISPRIMEMESSAGE = DESCRIPTOR.message_types_by_name['IsPrimeMessage']
_ISPRIMEMESSAGERESPONSE = DESCRIPTOR.message_types_by_name['IsPrimeMessageResponse']
ReverseMessage = _reflection.GeneratedProtocolMessageType('ReverseMessage', (_message.Message,), {
  'DESCRIPTOR' : _REVERSEMESSAGE,
  '__module__' : 'Service_pb2'
  # @@protoc_insertion_point(class_scope:ReverseMessage)
  })
_sym_db.RegisterMessage(ReverseMessage)

ReverseMessageResponse = _reflection.GeneratedProtocolMessageType('ReverseMessageResponse', (_message.Message,), {
  'DESCRIPTOR' : _REVERSEMESSAGERESPONSE,
  '__module__' : 'Service_pb2'
  # @@protoc_insertion_point(class_scope:ReverseMessageResponse)
  })
_sym_db.RegisterMessage(ReverseMessageResponse)

SplitMessage = _reflection.GeneratedProtocolMessageType('SplitMessage', (_message.Message,), {
  'DESCRIPTOR' : _SPLITMESSAGE,
  '__module__' : 'Service_pb2'
  # @@protoc_insertion_point(class_scope:SplitMessage)
  })
_sym_db.RegisterMessage(SplitMessage)

SplitMessageResponse = _reflection.GeneratedProtocolMessageType('SplitMessageResponse', (_message.Message,), {
  'DESCRIPTOR' : _SPLITMESSAGERESPONSE,
  '__module__' : 'Service_pb2'
  # @@protoc_insertion_point(class_scope:SplitMessageResponse)
  })
_sym_db.RegisterMessage(SplitMessageResponse)

IsPrimeMessage = _reflection.GeneratedProtocolMessageType('IsPrimeMessage', (_message.Message,), {
  'DESCRIPTOR' : _ISPRIMEMESSAGE,
  '__module__' : 'Service_pb2'
  # @@protoc_insertion_point(class_scope:IsPrimeMessage)
  })
_sym_db.RegisterMessage(IsPrimeMessage)

IsPrimeMessageResponse = _reflection.GeneratedProtocolMessageType('IsPrimeMessageResponse', (_message.Message,), {
  'DESCRIPTOR' : _ISPRIMEMESSAGERESPONSE,
  '__module__' : 'Service_pb2'
  # @@protoc_insertion_point(class_scope:IsPrimeMessageResponse)
  })
_sym_db.RegisterMessage(IsPrimeMessageResponse)

_SERVICE = DESCRIPTOR.services_by_name['Service']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REVERSEMESSAGE._serialized_start=17
  _REVERSEMESSAGE._serialized_end=47
  _REVERSEMESSAGERESPONSE._serialized_start=49
  _REVERSEMESSAGERESPONSE._serialized_end=90
  _SPLITMESSAGE._serialized_start=92
  _SPLITMESSAGE._serialized_end=135
  _SPLITMESSAGERESPONSE._serialized_start=137
  _SPLITMESSAGERESPONSE._serialized_end=190
  _ISPRIMEMESSAGE._serialized_start=192
  _ISPRIMEMESSAGE._serialized_end=224
  _ISPRIMEMESSAGERESPONSE._serialized_start=226
  _ISPRIMEMESSAGERESPONSE._serialized_end=264
  _SERVICE._serialized_start=267
  _SERVICE._serialized_end=433
# @@protoc_insertion_point(module_scope)
